<?php

declare(strict_types=1);

/**
 * @file
 * Provides an user registry entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function user_registry_theme(): array {
  return [
    'user_registry' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for user registry templates.
 *
 * Default template: user-registry.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user registry information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_user_registry(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function user_registry_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_reassign':
      // Anonymize user registries.
      $storage = \Drupal::entityTypeManager()->getStorage('user_registry');
      $user_registry_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($user_registry_ids) as $user_registry) {
        $user_registry->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function user_registry_user_predelete(UserInterface $account): void {
  // Delete user registries that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('user_registry');
  $user_registry_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($user_registry_ids)
  );
}
