# Schema for the configuration files of the User Registry* module.
user_registry.settings:
  type: config_object
  label: 'User Registry* settings'
  mapping:
    example:
      type: string
      label: 'Example'
